### ISSUE TITLE
TypeError: flower() got an unexpected keyword argument 'ini_var'

### ISSUE THREAD

**Issue by dpdoughe** [sontek/pyramid_celery#100]
With pyramid-celery==4.0.0,  celery==5.2.3 and flower=1.0.0 I'm getting the error after invoking flower via
```
celery -A pyramid_celery.celery_app flower
```
It seems like pyramid-celery is trying to send ini_var parameter with the newer version of flower no longer accepts.

Stack trace is
```
flower_1      | Traceback (most recent call last):
flower_1      |   File "/usr/local/bin/celery", line 8, in <module>
flower_1      |     sys.exit(main())
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/celery/__main__.py", line 15, in main
flower_1      |     sys.exit(_main())
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 213, in main
flower_1      |     return celery(auto_envvar_prefix="CELERY")
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1128, in __call__
flower_1      |     return self.main(*args, **kwargs)
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1053, in main
flower_1      |     rv = self.invoke(ctx)
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1659, in invoke
flower_1      |     return _process_result(sub_ctx.command.invoke(sub_ctx))
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1395, in invoke
flower_1      |     return ctx.invoke(self.callback, **ctx.params)
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 754, in invoke
flower_1      |     return __callback(*args, **kwargs)
flower_1      |   File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
flower_1      |     return f(get_current_context(), *args, **kwargs)
flower_1      | TypeError: flower() got an unexpected keyword argument 'ini_var'
```

**Comment by dpdoughe** [comment]
Update: I found the following work-around.

Changing the invocation to 
```
celery flower -A pyramid_celery.celery_app
```
instead of 
```
celery -A pyramid_celery.celery_app flower
````
seems to get things back running.  Not sure if this is generally recommended solution  however. Perhaps there is a bug as mentioned above.

**Comment by dpdoughe** [comment]
Purge, shell, inspect, and flower have been restored to accepting ini options from Pyramid-Celery as a result of resolution of https://github.com/celery/celery/pull/8374

**Comment by dpdoughe** [comment]
Purge, shell, inspect, and flower have been restored to accepting ini options from Pyramid-Celery as a result of resolution of https://github.com/celery/celery/pull/8374
