### ISSUE TITLE
Unable to run purge with Celery release candidate 5.3.0rc1

### ISSUE THREAD

**Issue by dpdoughe** [sontek/pyramid_celery#101]
Lot's of changes in Celery have been happening since the last release of pyramid-celery. Recently building against Celery==5.3.0rc1
and pyramid-celery v4.0.0 I run into the following problems with purge

Without --ini arg specified I get the error

```
celery -A pyramid_celery.celery_app purge
You must provide the paste --ini argument
```

and when running with --ini specified

```
celery -A pyramid_celery.celery_app purge --ini ini/staging.ini
Traceback (most recent call last):
  File "/usr/local/bin/celery", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/celery/__main__.py", line 15, in main
    sys.exit(_main())
  File "/usr/local/lib/python3.8/dist-packages/celery/bin/celery.py", line 235, in main
    return celery(auto_envvar_prefix="CELERY")
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/celery/bin/base.py", line 134, in caller
    return f(ctx, *args, **kwargs)
TypeError: purge() got an unexpected keyword argument 'ini'
```

It seems that pyramid-celery is requiring --ini but it is no longer supported or required by the upstream Celery method

**Comment by dpdoughe** [comment]
Note the error `You must provide the paste --ini argument` is coming from pyramid-celery here  https://github.com/sontek/pyramid_celery/blob/cf8aa80980e42f7235ad361874d3c35e19963b60/pyramid_celery/__init__.py#L105

while the `got an unexpected keyword argument 'ini'` is coming from Celery

**Comment by dpdoughe** [comment]
I'm wondering if a possible path forward is instead of using a `preload` options, which seem to add these options to all commands, 

```
celery_app.user_options['preload'].add()
```
e.g.,  https://github.com/sontek/pyramid_celery/blob/cf8aa80980e42f7235ad361874d3c35e19963b60/pyramid_celery/__init__.py#L25-L36

you could instead specify which particular commands should use your ini and ini_var options as mentioned in https://github.com/celery/celery/blob/e7b47a62d789557cf18ed0e56e2dfb99a51a62f7/docs/userguide/extending.rst#adding-new-command-line-options

```
        ini_option = Option(
            ('--ini', '-i',),
            help='Paste ini configuration file.'
        )
        ini_var_option = Option(
            ('--ini-var',),
            help='Comma separated list of key=value to pass to ini.'
        )
        # TODO: Add "shell" to list if Celery developers will add the "allow_extra_args" 
        # context flag to shell command  
        # https://github.com/celery/celery/blob/f3a2cf45a69b443cac6c79a5c85583c8bd91b0a3/celery/bin/shell.py#L82
        for option in ['worker','beat']:
            celery_app.user_options[option].add(
                ini_option
            )
            celery_app.user_options[option].add(
                ini_var_option
            )
``` 
This approach does seem to be working fine for me because Celery's Beat and Worker command already specify 
```
context_settings={
    'allow_extra_args': True
}
```
See for example: https://github.com/celery/celery/blob/f3a2cf45a69b443cac6c79a5c85583c8bd91b0a3/celery/bin/beat.py#L11

I left a TODO above because, currently this isn't working for the `shell` command because Celery does not (yet) specify `allow_extra_args` in its context settings. See e.g., https://github.com/celery/celery/blob/f3a2cf45a69b443cac6c79a5c85583c8bd91b0a3/celery/bin/shell.py#L82

I've verified this solution works for `worker` and `beat` commands already and the Celery docs suggest it will work for `events` command too. If a feature request were made to Celery for the change to `shell` command to add the `allow_extra_args`, do you think this could provide a path forward?

**Comment by dpdoughe** [comment]
Also, correct me if I am wrong, while `shell` does need `ini` interaction, to get all the registered tasks, it doesn't seem like `purge` functionality would require `ini` interaction.

**Comment by dpdoughe** [comment]
I've created a feature request ticket in Celery https://github.com/celery/celery/issues/8259

**Comment by dpdoughe** [comment]
@sontek, can you comment on the proposed approach?

**Comment by dpdoughe** [comment]
The Celery project has now officially release their 5.3.1 https://pypi.org/project/celery/5.3.1

This inability to configure and run `purge` or `shell` commands with pyramid_celery persists with Celery v5.3.1

**Comment by dpdoughe** [comment]
@sontek my pull request to Celery has been merged bringing back preload options support for purge and shell. See https://github.com/celery/celery/pull/8374 

I believe no code changes will be needed in pyramid-celery. We still need to confirm once a new release of Celery is available.

**Comment by dpdoughe** [comment]
Purge, shell, inspect etc have been restored to accepting ini options from Pyramid-Celery as a result of resolution of https://github.com/celery/celery/pull/8374
