### ISSUE TITLE
Can't set CELERY_ACCEPT_CONTENT parameter through the ini file (will be blocking with celery 3.2)

### ISSUE THREAD

**Issue by tonthon** [sontek/pyramid_celery#48]
In pyramid_celery 2.0.0-rc3, while configuring through the main ini file, it's not possible to configure CELERY_ACCEPT_CONTENT

The ini file content
```
CELERY_ACCEPT_CONTENT =
     json
```

The traceback
```
Traceback (most recent call last):
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/billiard/process.py", line 292, in _bootstrap
    self.run()
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/billiard/pool.py", line 286, in run
    self.after_fork()
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/billiard/pool.py", line 389, in after_fork
    self.initializer(*self.initargs)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/concurrency/prefork.py", line 81, in process_initializer
    app=app)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/app/trace.py", line 161, in build_tracer
    backend = task.backend
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/five.py", line 284, in __get__
    return self.__get.__get__(obj, type)()
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/task/base.py", line 75, in backend
    return cls.app.backend
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/kombu/utils/__init__.py", line 322, in __get__
    value = obj.__dict__[self.__name__] = self.__get(obj)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/app/base.py", line 625, in backend
    return self._get_backend()
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/app/base.py", line 444, in _get_backend
    return backend(app=self, url=url)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/celery/backends/base.py", line 107, in __init__
    conf.CELERY_ACCEPT_CONTENT if accept is None else accept,
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/kombu/serialization.py", line 454, in prepare_accept_content
    return set(n if '/' in n else name_to_type[n] for n in l)
  File "/home/gas/.virtualenvs/autonomie/lib/python2.7/site-packages/kombu/serialization.py", line 454, in <genexpr>
    return set(n if '/' in n else name_to_type[n] for n in l)
KeyError: '\n'
```

Expected CELERY_IMPORTS (a specific treatment has been added in the pyramd_celery/__init__.py file), we can't customize parameters expecting a list as value.

**Comment by sontek** [comment]
@tonthon  Pushed `-rc4` with a fix for this.  Please set me know if that helps and then I will close this issue

**Comment by sontek** [comment]
This is fixed in rc4

**Comment by tonthon** [comment]
Thanks a lot for the fix (I confirm it's ok)
